version: '3.7'

services:
  bcd-api:
    image: bakingbad/bcdhub-api:3.5
    environment:
      - BCD_ENV=sandbox
      - GIN_MODE=debug
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - SANDBOX_NODE_URI=http://sandbox:20000 # Optional key to point to sandbox
    depends_on:
      - db
      - bcd-indexer
    ports:
      - 42000:14000
    restart: on-failure
    logging:
      options:
        max-size: 10m
        max-file: '5'

  bcd-indexer:
    image: bakingbad/bcdhub-indexer:3.5
    environment:
      - BCD_ENV=sandbox
      - GIN_MODE=debug
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - SANDBOX_NODE_URI=http://sandbox:20000 # Optional key to point to sandbox
    depends_on:
      - elastic
      - mq
      - sandbox
    logging:
      options:
        max-size: 10m
        max-file: '5'

  tzkt-api:
    container_name: tzkt-api
    restart: always
    image: bakingbad/tzkt-api:latest
    volumes:
      - ./docker/tzkt-api-appsettings.json:/app/appsettings.json
    depends_on:
      - db
      - tzkt-sync
    expose:
      - 5000
    ports:
      - 0.0.0.0:5000:5000

  tzkt-sync:
    container_name: tzkt-sync
    restart: always
    image: bakingbad/tzkt-sync:latest
    volumes:
      - ./docker/tzkt-sync-appsettings.json:/app/appsettings.json
    depends_on:
      - db
      - sandbox

  db:
    image: postgres
    volumes:
      - ./docker/multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/multiple-postgresql-databases.sh
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_MULTIPLE_DATABASES: bcd,tzkt
    ports:
      - 5432:5432

  mq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    logging:
      options:
        max-size: 10m
        max-file: '5'

  elastic:
    image: bakingbad/bcdhub-elastic:3.5
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    logging:
      options:
        max-size: 10m
        max-file: '5'

  # Flextesa is included only to support running this docker-compose file with
  # a sandbox node
  sandbox:
    image: tqtezos/flextesa:20210514
    environment:
      block_time: 5
      flextesa_node_cors_origin: "*"
    command: "flobox start --keep-root"
    ports:
      - 8732:20000

  ipfs:
    image: ipfs/go-ipfs
    ports:
      - 8080:8080
      - 4001:4001
      - 5001:5001

  minter-api:
    image: tqtezos/minter-api:latest
    ports:
      - 3300:3300
    volumes:
      - ./config/minter-api.sandbox.json:/usr/src/app/server/config.json
